--初始化菜单表
DROP TABLE IF EXISTS T_MENU;
CREATE TABLE T_MENU (
  ID VARCHAR(64) PRIMARY KEY,
  NAME VARCHAR(64),
  URL VARCHAR(128),
  ADMIN VARCHAR(5)
);
INSERT INTO T_MENU  VALUES('main', '主页', '/main.action', 'false');
INSERT INTO T_MENU  VALUES('data', '数据管理', '/data/list.action', 'false');
INSERT INTO T_MENU  VALUES('user', '用户管理', '/user/list.action', 'true');
INSERT INTO T_MENU  VALUES('role', '角色管理', '/role/list.action', 'true');

-- 初始化资源表
DROP TABLE IF EXISTS T_RESOURCES;
CREATE TABLE T_RESOURCES (
  ID VARCHAR(64) PRIMARY KEY,
  NAME VARCHAR(64),
  MENU_ID VARCHAR(64)
);

-- 初始化角色表
DROP TABLE IF EXISTS T_ROLE;
CREATE TABLE T_ROLE (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(64),
  CREATETIME TIMESTAMP,
  DESC VARCHAR(512)
);
INSERT INTO T_ROLE  VALUES(0, '管理员', now(), '系统管理员角色');

-- 初始化角色资源映射表
DROP TABLE IF EXISTS T_ROLE_RESOURCES;
CREATE TABLE T_ROLE_RESOURCES (
  ROLE_ID INT,
  RESOURCES_ID INT
);

--初始化用户表
DROP TABLE IF EXISTS T_USER;
CREATE TABLE T_USER (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  USERNAME VARCHAR(64),
  PASSWORD VARCHAR(64),
  ADMIN VARCHAR(5),
  CREATETIME TIMESTAMP,
  DESC VARCHAR(512),
  CONSTRAINT UC_USERNAME UNIQUE (USERNAME)
);
INSERT INTO T_USER  VALUES(1, 'admin', '21232f297a57a5a743894a0e4a801fc3', 'true', now(),'admin');
INSERT INTO T_USER  VALUES(2, 'ums', '21232f297a57a5a743894a0e4a801fc3', 'false', now(),'ums');
